### PR TITLE
adding cocotb tests 

### PR DESCRIPTION
**Pull request by M0stafaRady**
- Adding cocotb tests to test the GPIOs 
- Add some RTL changes to run the simulation all RTL changes are guarded by COCOTB_SIM

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
Probably it would be a good idea to list out all of the cocotb tests for Caravel and I can go through the list and select which ones are also appropriate to run on this Openframe project, and make notes about what modifications are needed to make it work for the various differences corresponding to the picoRV32 core.

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
There are multiple issues with this pull request:  (1) there should be no mention of VexRISC anywhere in the code.  Why is this now being defined?  (2) There should be no mention of MGMT or USER anything.  Why are these no-longer-valid GPIO codes being defined?  There are only the GPIO_MODE_* definitions for this design.  (3) Why would anyone use "enum" for a set of values that are not enumerated?  (4) The debug registers are actually a very small addition.  Should they be just be a part of the design and not just defined for cocotb?  Wouldn't that make it easier to map the existing cocotb tests to silicon bench tests?  It would also remove a lot of ugly "ifdef" statements from the code base.

This may not be a full list of issues because I don't have the time to check more thoroughly right now.  I'll take a closer look at it later.

**Comment by M0stafaRady** [comment]
> There are multiple issues with this pull request: (1) there should be no mention of VexRISC anywhere in the code. Why is this now being defined? (2) There should be no mention of MGMT or USER anything. Why are these no-longer-valid GPIO codes being defined? There are only the GPIO_MODE_* definitions for this design. (3) Why would anyone use "enum" for a set of values that are not enumerated? (4) The debug registers are actually a very small addition. Should they be just be a part of the design and not just defined for cocotb? Wouldn't that make it easier to map the existing cocotb tests to silicon bench tests? It would also remove a lot of ugly "ifdef" statements from the code base.
> 
> This may not be a full list of issues because I don't have the time to check more thoroughly right now. I'll take a closer look at it later.

1) The CPU type is used by the scripts to determine which compiler to use to compile the C code. It can support Risc and ARM compilers for now. 
2) This is a compatibility issue in order to share the same configurations values between the testbench and the design they must be defined but I guess I can remove this dependency it's just I never though I might need to. 
3)  I mainly use enum to define a fixed set of values so no one can pass illegal values to the APIs that configure the GPIOs 
4) yes, I totally agree with you.

**Comment by M0stafaRady** [comment]
here is a list of the features verified by cocotb caravel : 

1. gpio configurations using automatic, bitbang and SPI
2. UART
3. housekeeping registers access through SPI
4. housekeeping registers access through wishbone 
5. IRQs 
6. timer 
7. debug interface 
8. SPI master
9. memory 
10.  spi modes like nbytes commands and user pass thru 
11. PoR 
12. managment gpio 
13. clock redirecting 
14. logic analyzers 


Can you choose which of these features are common between caravel and this repo and if there are other features that can be verified ?

**Comment by RTimothyEdwards** [comment]
@M0stafaRady :  Going back to the four points above, since I didn't get a chance to follow up on your response before now:
(1) I understand the need for a CPU type.  But this is not a VexRISC and the compiler needs to know that it is a RISC-V processor of type rv32imc rather than rv32i.
(2) I would definitely prefer that in openframe there should be zero dependencies on anything that relates to "user" or "management", since those concepts don't exist in openframe (the removal of dependencies is going to have to happen eventually since the end goal is to have the openframe in its own repository).
(3) All values are legal, therefore enumeration is not appropriate.  The definitions correspond only to the most useful modes, not all possible legal modes.

**Comment by RTimothyEdwards** [comment]
Tests that are common to caravel and this openframe project:
@M0stafaRady :  These are the tests that are common to both caravel and openframe:
-     UART (but picorRV32 module is slightly different)
-     housekeeping registers access through SPI
-     housekeeping registers access through wishbone
-     IRQs (picoRV32 implementation is slightly different)
-     timer (but uses a different timer)
-     SPI master (but users a different SPI master module)
-     memory (except size is different)
-     spi modes like nbytes commands (no user pass-through.  managment pass-through is valid but just called "pass-through").
-     PoR
-     clock redirecting

**Comment by M0stafaRady** [comment]
I have addressed the 4 points above. Can you check them ?

**Comment by M0stafaRady** [comment]
I don't understand how the `GPIO_MODE_BIDIRECTIONAL` mode works. Is there a special signal that determine which direction it would work as ?

**Comment by RTimothyEdwards** [comment]
"bidirectional mode" means only that the OEB line is controlled by an application and not fixed 1 or 0.  The GPIO control for this openframe project has in/out/oeb signal inputs coming from the "GPIO array" register, so if not overridden by setting the OEB override bit, then a program can use the GPIO array registers to switch the GPIO direction quickly from an application by writing to the OEB array register.  Whenever the "OEB override" bit is set, then the OEB is fixed.  This is a rather fine distinction, since the direction can be changed from a program either way.  The difference is that when using the GPIO array registers, many registers can be set or read or have their direction changed on the same clock cycle, so it's much faster than changing the individual configuration for each GPIO.  Furthermore, the individual GPIO configuration bits are handled by the housekeeping module, so not only must they be changed one at a time, but it takes multiple clock cycles for the housekeeping to change each register, which it does in 8-bit groups.

**Comment by RTimothyEdwards** [comment]
Mainly I'm using the openframe project to play around with different ways of handling the GPIO (and other IP) which I might want to apply back to caravel sometime if they seem to be useful.

**Comment by RTimothyEdwards** [comment]
@M0stafaRady: Last items:
(1) Lines 200 and following and lines 715 and following still use ifdefs for the debug registers, although you removed the earlier references.
(2) You have a reference to your own home directory in the cocotb code (I think I also have a reference to my own home directory somewhere).  Since there's only one repository here, it should probably get the directory reference from the current working directory.

**Comment by M0stafaRady** [comment]
>  (2) You have a reference to your own home directory in the cocotb code (I think I also have a reference to my own home directory somewhere). Since there's only one repository here, it should probably get the directory reference from the current working directory.

This reference will change by running the cocotb running script. I have to do that because the running flow and APIs are not an installable package yet.

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.

**Pull request merged**
