### PR TITLE
RTL updates 

### PR DESCRIPTION
**Pull request by M0stafaRady**
- Fix for https://github.com/RTimothyEdwards/caravel_openframe_project/issues/17 
- Fix for https://github.com/RTimothyEdwards/caravel_openframe_project/issues/16 
- Change the base address for interrupt in PicoRV32 
- The PR has common cocotb changes with https://github.com/RTimothyEdwards/caravel_openframe_project/pull/14

### CODE REVIEW

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
(1) What is the reasoning behind changing PROGADDR_IRQ to an address in SPI flash instead of in main memory?  I have written IRQ testbenches that work with the address value zero, and they are very fast interrupt routines that operate directly out of main memory.

(2) I do not understand the rationale behind changing the timer code at lines 174-177.  It cannot be right.  The wishbone register associated with "reg_val_" should be written on the write enable associated with the same register, not a different one.

Please justify your changes.

**Comment by M0stafaRady** [comment]
> (1) What is the reasoning behind changing PROGADDR_IRQ to an address in SPI flash instead of in main memory? I have written IRQ testbenches that work with the address value zero, and they are very fast interrupt routines that operate directly out of main memory.

I didn't know that main memory could used  to provide instruction very fast. Could you point me to this testbench please ? 
What I did is changing the [start.S](https://github.com/YosysHQ/picorv32/blob/master/firmware/start.S) file to match what guys in [YosysHQ](https://github.com/YosysHQ) do. The start file changes could be found in this [commit](https://github.com/M0stafaRady/caravel_openframe_project/commit/d9939431099fea06d9f633ba616ec7d80c58f2be) . This change has been tested for all types of interrupts spi, external1 , external2, timer interrupt and spi interrupt.

**Comment by M0stafaRady** [comment]
> (2) I do not understand the rationale behind changing the timer code at lines 174-177. It cannot be right. The wishbone register associated with "reg_val_" should be written on the write enable associated with the same register, not a different one.

I had a wrong understanding of the functionality of the data and value register. This change doesn't make sense after I reviewed the RTL again. I have already reverted it.

**Comment by RTimothyEdwards** [comment]
@M0stafaRady :  Probably the change to the interrupt location is fine, especially if YosysHQ did the same thing.  The location was originally set to zero because that's what was in the picosoc example.  It works but is a bit awkward to set up.

**Review by RTimothyEdwards — APPROVED** [review]
Okay, this all looks good to me now.

**Pull request merged**
